export const FALLBACK_GROUPS = [
  { id: "1", name: "Bethel CareGroup-01", meetingDay: "Sunday", meetingTime: "14:00", location: "Willenhall", memberCount: 12, healthScore: 92 },
  { id: "2", name: "Bethel CareGroup-02", meetingDay: "Wednesday", meetingTime: "18:30", location: "Dudley", memberCount: 10, healthScore: 85 },
  { id: "3", name: "Bethel CareGroup-03", meetingDay: "Tuesday", meetingTime: "19:00", location: "Birmingham", memberCount: 15, healthScore: 78 },
  { id: "4", name: "Bethel CareGroup-04", meetingDay: "Thursday", meetingTime: "19:30", location: "Wolverhampton", memberCount: 8, healthScore: 70 },
  { id: "5", name: "Bethel CareGroup-05", meetingDay: "Monday", meetingTime: "18:00", location: "Walsall", memberCount: 11, healthScore: 88 },
  { id: "6", name: "Bethel CareGroup-06", meetingDay: "Saturday", meetingTime: "10:00", location: "Coventry", memberCount: 9, healthScore: 75 },
  { id: "7", name: "Bethel CareGroup-07", meetingDay: "Tuesday", meetingTime: "19:30", location: "Sandwell", memberCount: 13, healthScore: 82 },
  { id: "8", name: "Bethel CareGroup-08", meetingDay: "Thursday", meetingTime: "18:00", location: "West Bromwich", memberCount: 7, healthScore: 68 },
  { id: "9", name: "Bethel CareGroup-09", meetingDay: "Sunday", meetingTime: "15:00", location: "Stourbridge", memberCount: 10, healthScore: 80 },
  { id: "10", name: "Bethel CareGroup-10", meetingDay: "Wednesday", meetingTime: "19:00", location: "Halesowen", memberCount: 14, healthScore: 90 },
];

// Simple users WITHOUT bcrypt - using plain text passwords for now
export const FALLBACK_USERS = [
  {
    id: "admin-1",
    username: "admin",
    email: "admin@bethelwillenhall.org.uk",
    name: "System Administrator",
    role: "ADMIN",
    groupId: "all",
    password: "admin@Bwcg777",  // Plain text password
    isActive: true,
  },
  {
    id: "pastor-dan-1",
    username: "PastorDan",
    email: "dan.majaducon@bethelwillenhall.org.uk",
    name: "Pastor Dan Majaducon",
    role: "PASTOR",
    groupId: "all",
    password: "PastorDan@BWcg777",
    isActive: true,
  },
  {
    id: "pastor-tm-1",
    username: "PastorTM",
    email: "thando.mlalazi@bethelwillenhall.org.uk",
    name: "Pastor Thando Mlalazi",
    role: "PASTOR",
    groupId: "all",
    password: "PastorTM@BWcg777",
    isActive: true,
  },
  {
    id: "coord-01-1",
    username: "CG-coord-01",
    email: "coordinator1@bethelwillenhall.org.uk",
    name: "Coordinator CG-01",
    role: "COORDINATOR",
    groupId: "1",
    password: "CG-coord-01@BWcg04",
    isActive: true,
  },
  {
    id: "coord-02-1",
    username: "CG-coord-02",
    email: "coordinator2@bethelwillenhall.org.uk",
    name: "Coordinator CG-02",
    role: "COORDINATOR",
    groupId: "2",
    password: "CG-coord-02@BWcg04",
    isActive: true,
  },
  {
    id: "coord-03-1",
    username: "CG-coord-03",
    email: "coordinator3@bethelwillenhall.org.uk",
    name: "Coordinator CG-03",
    role: "COORDINATOR",
    groupId: "3",
    password: "CG-coord-03@BWcg04",
    isActive: true,
  },
  {
    id: "member-01-1",
    username: "Member@BWcg",
    email: "member@bethelwillenhall.org.uk",
    name: "Care Group Member",
    role: "MEMBER",
    groupId: "1",
    password: "Member@BWcg@member",
    isActive: true,
  },
];
